spring.application.name=Inventory
spring.datasource.url=jdbc:mysql://localhost:3306/newEcommerce?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrival=true
spring.datasource.username=root
spring.datasource.password=Khushimysql@123
spring.jpa.hibernate.ddl-auto=update
server.port=8081